### ISSUE TITLE
Newbie: please explain pathMappings

### ISSUE THREAD

**Issue by eghoff1** [xdebug/vscode-php-debug#254]
Hi there. I am a complete newbie with php and vscode and xdebug. I put in my localSourceRoot and ServerRoot but the Intellisense tells me that it is deprecated and to use pathMappings instead.

I have no idea what information to put in the places requested. Please explain what each term is in pathMappings.

This is what I've got so far,  but I don't know what the first "/app/public" is supposed to be.
"pathMappings": {
"/app/public": "${workspaceRoot}c:/wamp64/www/wp_new/wordpress"

I've read other discussions/posts and even have been exhausting my efforts with google but still have no idea what I am doing.
}

PHP version:  7.1.9
XDebug version:  2.6.0.6
Adapter version:  What adapter?

Your launch.json:  {
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000,
            "pathMappings": {
                "/app/public": "${workspaceRoot}c:/wamp64/www/wp_new/wordpress"
            }
            //"/path/on/server": "${workspaceRoot}/local/path"
            
            //"localSourceRoot": "C:/wamp64/www/wp_new/wordpress",
          //  "serverSourceRoot": "C:/wamp64/www/wp_new/wordpress"
        }
    ]
}
XDebug php.ini config:  ; XDEBUG Extension
[xdebug]
; zend_extension ="c:/wamp64/bin/php/php7.1.9/zend_ext/php_xdebug-2.5.5-7.0-vc14-x86_64.dll"
zend_extension="c:/wamp64/bin/php/php7.1.9/zend_ext/php_xdebug-2.6.0-7.1-vc14-nts-x86_64.dll"

xdebug.remote_enable = on
xdebug.profiler_enable = off
xdebug.profiler_enable_trigger = Off
xdebug.profiler_output_name = cachegrind.out.%t.%p
xdebug.profiler_output_dir ="c:/wamp64/tmp"
xdebug.remote_port = 9000
xdebug.remote_host = localhost
xdebug.show_local_vars=0

XDebug logfile (from setting `xdebug.remote_log` in php.ini):  
Adapter logfile (from setting `"log": true` in launch.json):  

Code snippet to reproduce:  
```php

```

**Comment by eghoff1** [comment]
Thank you, kajes, I can only hope this fixes the problem I'm having.

**Comment by JonFranchi** [comment]
I think explanation of what these are supposed to be would be helpful.  You have a set of Key value pairs where everything is a variable and nothing is obvious.  I am using this remote and cannot make heads or tails of what I am supposed to set these to or how the tool would even have access to know these paths in the remote server.  What do they map to?  I get that workspaceroot is effectively a pwd for the workspace.

**Comment by intellix** [comment]
This was all working for me until recently. Have no idea how to even debug xdebug but it just doesn't work. Nothing changed in config and now I'm seeing that this is marked as deprecated: 

```
```

**Comment by feryardiant** [comment]
> It says to use pathMappings instead but what's supposed to go on the left?

@intellix the left side is the path on your remote I guess. Honestly I personally not sure if my answer is correct, since I fairly new to this extension. But in my case I'm using WSL and it works that way.

Let say, from Windows side my project is located in `d:\path\to\project` and from WSL side we'll see it located in `/mnt/d/path/to/project` so I set my `pathMappings` like this

```json
"pathMappings": {
  "/mnt/d/Workspaces/personal/creasico/playgrounds/l5bp/app": "${workspaceRoot}/app"
}
```

and it works.

Hope that help. Cheers 🥂

**Comment by rkaiser0324** [comment]
I'm new to VS.Code but have done a lot of PHP debugging elsewhere.  I think there might be some terminology confusion here related to workspaces, since I ran into a similar headache setting this up.  This is what I figured out.

To use the above example, assume that the path to a given file to debug on the server is `/mnt/d/path/to/project/app/index.php`, and that in the current workspace in VS.Code, you've added the local folder `app`.  I would have expected to set `pathMappings` as

```
"pathMappings": {
                "/mnt/d/path/to/project/app": "${workspaceRoot}/app"
            },
```

but you actually should set it as

```
"pathMappings": {
                "/mnt/d/path/to/project/app": "${workspaceRoot}"
            },
```

**Comment by eghoff1** [comment]
Thank you, Rolf, for helping. I will look into it the next time I open VSCode.

Thanks again.

In your debt,
Eric Hoff

**Comment by j-gimbel** [comment]
> 
> 
> I'm new to VS.Code but have done a lot of PHP debugging elsewhere. I think there might be some terminology confusion here related to workspaces, since I ran into a similar headache setting this up. This is what I figured out.
> 
> To use the above example, assume that the path to a given file to debug on the server is `/mnt/d/path/to/project/app/index.php`, and that in the current workspace in VS.Code, you've added the local folder `app`. I would have expected to set `pathMappings` as
> 
> ```
> "pathMappings": {
>                 "/mnt/d/path/to/project/app": "${workspaceRoot}/app"
>             },
> ```
> 
> but you actually should set it as
> 
> ```
> "pathMappings": {
>                 "/mnt/d/path/to/project/app": "${workspaceRoot}"
>             },
> ```

Wow. Found this after one hour trying to get xdebug to work. 
Felix, I suggest you could myabe update/clarify the extension description in vscode ?
Many thanks for your great work!

**Comment by borishuseincehajic** [comment]
Hi, I have trouble with proper mapping. I'm on Mac currently and since docker for mac has poor performance (I haven't been able to set it up to be smooth as it can be on Linux etc.) I'm using vagrant and then inside vagrant I have docker installed. Using devilbox http://devilbox.org/. 
I know that the mappings for the devilbox would be this:

`"pathMappings": {
                "/shared/httpd/arktisCH/htdocs": "${workspaceFolder}/htdocs"
   }`

But I have additional layer of mapping needed as vagrant has its own mapping and has this setup:
`  config.vm.synced_folder './public', '/vagrant-nfs', type: "nfs",
    config.bindfs.bind_folder "/vagrant-nfs", "/home/vagrant/docker"`

Now I'm not sure even if its possible to activate the xDebug with this setup at all? Any help appriciated.

**Comment by adjenks** [comment]
If anyone else is crying about pathmappings in vs code, this solved it for me:

I tried everyhing, this **did not** work:
```
	"pathMappings": {
		"\\my_remote_file_share\\my_root": "${fileDirname}"
	}
```
This **did** work:
```
	"pathMappings": {
		"/my_remote_file_share/my_root": "${fileDirname}"
	}
```
So even though I was running php locally on a _Windows_ machine, it required that I use forward slashes. Only forward slashes would work.

My full config looks like this:
```
	{
		"name": "Launch currently open script",
		"type": "php",
		"request": "launch",
		"runtimeExecutable": "C:\\PHP\\php.exe",
		"program": "${file}",
		"cwd": "${fileDirname}",
		"port": 9003,
		"pathMappings": {
		        "/my_remote_file_share/my_root": "${fileDirname}"
	        }
	}
```

I'm running the files locally so I don't see why I need to map any paths, nothing is being compiled or built or transpiled or moved, the stack trace even shows exactly where the files are when an error occurs, so it makes no sense that they would be mangled...

Anyways, happy coding, or whatever I guess...

**Comment by zobo** [comment]
If you run locally on windows (no docker or something) there should be no need for pathMapptings. I'd appreciate a log and config to test this. Closing for now, please open a new issue with details and I'll also update docs from there.

**Comment by mikkorantalainen** [comment]
According to some comments, breakpoints in files within subdirectories may not work unless you add some wildcard settings, too.

Let's say the file you're working with are in local directory /home/johndoe/git-repositories/site1/index.php and the same git repository with that file is syncronized to remote server in directory /var/www/code/site1/index.php, then you would want to use following config for remote debugging:

VS code `launch.json`:
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Listen for Xdebug localhost:9000",
			"type": "php",
			"request": "launch", // or attach? see https://code.visualstudio.com/docs/editor/debugging#_launch-configurations
			"port": 9000,
			// Tell VS Code how to map server -> local workspace, see also https://stackoverflow.com/questions/49582866/setting-up-vscode-with-xdebug-pathmapping
			"pathMappings":
			{
				"/var/www/code/site1": "${workspaceRoot}",
				"/var/www/code/site1/": "${workspaceRoot}/", // logically shouldn't be needed
				"/var/www/code/site1/**": "${workspaceRoot}/**", // logically shouldn't be needed
			},
		},
	]
}
```
Combined with remote server configured with following XDebug settings in PHP ini files:
```
xdebug.remote_enable = 1
xdebug.remote_host = 127.0.0.1
xdebug.remote_port = 9000
xdebug.remote_handler = "dbgp"
```

**NOTE!** This results in remote server PHP trying to connect to localhost:9000 and your local (your own computer) VS Code is listening for localhost:9000 which doesn't obviously compute as-is because `localhost` is obviously local to each computer.  To *safely* debug remotely, you then want to connect these ports together with encrypted tunnel by running `ssh -R 9000:localhost:9000 myremotesite.example.com` which will open a remote shell and create encrypted tunnel from remote port 9000 to local port 9000 which will remain active until the shell is closed. I'm using this kind of config with local and remote systems both running Linux. I don't know how hard it would be to make encrypted tunneled ports to work with Windows system.

After this you can simply start debug session by loading the target page on any web browser with extra GET or POST argument `XDEBUG_SESSION_START=whatever` and stop the session with `XDEBUG_SESSION_STOP=whatever`.

**Comment by zobo** [comment]
Hi @mikkorantalainen.

The wildcard part makes no sense as pathMappings work on a prefix match basis.
See [convertClientPathToDebugger](https://github.com/xdebug/vscode-php-debug/blob/af38cb848f9ac5d2a3f44f94baf653250dba028b/src/paths.ts#L88) and [convertDebuggerPathToClient](https://github.com/xdebug/vscode-php-debug/blob/af38cb848f9ac5d2a3f44f94baf653250dba028b/src/paths.ts#L28).

You can also look at https://github.com/xdebug/vscode-php-debug/blob/main/src/test/paths.ts where various cases are tested.

**Comment by mikkorantalainen** [comment]
> The wildcard part makes no sense as pathMappings work on a prefix match basis. See [convertClientPathToDebugger](https://github.com/xdebug/vscode-php-debug/blob/af38cb848f9ac5d2a3f44f94baf653250dba028b/src/paths.ts#L88) and [convertDebuggerPathToClient](https://github.com/xdebug/vscode-php-debug/blob/af38cb848f9ac5d2a3f44f94baf653250dba028b/src/paths.ts#L28).
> 
> You can also look at https://github.com/xdebug/vscode-php-debug/blob/main/src/test/paths.ts where various cases are tested.

You're right, the current code and test cases do not show that they would be any need for multiple mappings to handle subdirectories. I also tested it with v1.30.0 on VS Code Version: 1.74.3. The lines that have comment `// logically shouldn't be needed` above are truly not needed at least with current release.

I'll add some new comments to sources that claim otherwise to reduce cargo cult programming a little bit.
