### ISSUE TITLE
[Bug] Extension ignore xdebug.scream parameters

### ISSUE THREAD

**Issue by Yivan** [xdebug/vscode-php-debug#385]
Hello,

Before all, thanks for providing us this nice extension!

I would like to report a bug.
The extension ignore xdebug.scream parameters, so using xdebug JIT feature make it break when it encounters a @ operator.
It should not as xdebug doc point it (see https://xdebug.org/docs/all_settings):

```
boolean xdebug.scream = false
Introduced in Xdebug >= 2.1

If this setting is 1, then Xdebug will disable the @ (shut-up) operator so that notices, warnings and errors are no longer hidden.
```

Please see:

![image](https://user-images.githubusercontent.com/9025839/71697811-7f876200-2db9-11ea-9717-94cec12ca7eb.png)

And actual config:

![image](https://user-images.githubusercontent.com/9025839/71697824-86ae7000-2db9-11ea-800b-df2124fe0fdb.png)

![image](https://user-images.githubusercontent.com/9025839/71697828-8c0bba80-2db9-11ea-8d37-40c0353c80af.png)

This issue has been raised to Symfony team here https://github.com/symfony/recipes/issues/717, as I was thinking it comes from Symfony using @ operator, but xdebug should not stop when it encounter @ operator, so it seems it is more related to this extension.

Thanks.

**Comment by Yivan** [comment]
@felixfbecker Any news on this please ?
Thanks.

**Comment by zobo** [comment]
I need to check this, but I don't think this setting has any effect on remote debugging.

**Comment by Yivan** [comment]
@zobo Thanks for looking into this ! I wait for your return so.
Best regards.

**Comment by zobo** [comment]
I have checked this and the `xdebug.scream` has no effect on remote debugging. Now, first, I'd personally not write code that generates warnings, even if there is the shut-up operator, but always wrap it in `file_exists`. 

That said, Notices, Warnings and Errors are an old PHP concept that's being replaced by Exceptions, so maybe just ignoring them by unticking Notices/Warnings/Errors breakpoint checkboxes cold be a solution for you? I understand this is very workflow/project dependent.
I have also discussed this issue with Xdebug author and we agree that disabling breakpoints by default makes most sense.

To actually solve this issue, we'd need to implement some complex logic issues:
- break ok E_WARNING, but ignore if on file/line location.

However, depending on your specific case, this could also be an option (see the main README):
> `ignore`: An optional array of glob patterns that errors should be ignored from (for example `**/vendor/**/*.php`)

This reference is also interesting: https://github.com/microsoft/vscode/issues/11552#issuecomment-291793725 but I'm not sure I can go into this direction...

I'll close this issue, since the `@` operator has no influence on debug sessions... Let me know if you can't solve your problem with the proposed methods and we can look more in-depth at your specific case.

**Comment by Yivan** [comment]
Thank you for your investigation and detailed answer.

I will try the direction you mention. If i get any problem I will let you know, but for now I confirm it can be closed.

Best regards.
