### ISSUE TITLE
break points take a very long time to show

### ISSUE THREAD

**Issue by SteveALee** [xdebug/vscode-php-debug#507]
PHP version: PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
Xdebug version: v3.0.2,
Adapter version: ?

Your launch.json:
```
    {
      // in CLI ./run-dev-server.sh and browse to localhost:8000
      "name": "gettoken page",
      "type": "php",
      "request": "launch",
      "port": 9003 // changed for xdebug 3.x
    }
```
Xdebug php.ini config:

```
[xdebug]
zend_extension = /usr/lib/php/20190902/xdebug.so
xdebug.mode = debug,develop
xdebug.start_with_request = yes
```

When I set a break point and run the code, the  VS Code icon flashes immediately, indicating the debugger has triggered but it takes some 10 seconds before the break point shows up with the stopped indicator.

Can I get any visibility in what might be happening?

Two factors might play a part.

- I'm on windows using VS Code Remote:WSL
-  I'm running the CLI built in debug server not Apache - run with `php -S localhost:8000 -t gettoken/`

Thanks

**Comment by zobo** [comment]
I have similar setups and no such problems. Can you provide log files? See https://github.com/xdebug/vscode-php-debug#troubleshooting and also know that Xdebug 3 changed configuration for remote log (see https://xdebug.org/docs/step_debug#troubleshoot). Should be `xdebug.log` instead of `xdebug.remote_log`.

Best,
Damjan

**Comment by SteveALee** [comment]
Will do. Thanks

**Comment by SteveALee** [comment]
@zobo Whatever the problem was it has resolved it self. It works perfectly and nice and fast too.
