### ISSUE TITLE
Noob Can't figure out UNC pathMappings and host setting - can't find examples to follow 

### ISSUE THREAD

**Issue by Wishville** [xdebug/vscode-php-debug#546]
Problem Statement:
 - Dev site hosted on synology WebStation vhost on e.g. dev.wordpress.com. This functions and is browsable
 - VS Code has remote folder in a workspace added via UNC for root of the vhost
 - Xdebug connects on "Launch currently open script" configuration , and I can see variables etc in debug panel but Code then attempts to open a non existent file
 - Noob cannot figure out the correct cimbinations 

PHP version: 7.4.9
Xdebug version: 2.9.6

Note: webserver Running on Synology NAS; limited ability to work around these versions without moving everything to Docker...

Client: Windows 10
 - VS Code Workspace
 - > Folder = UNC mapping e.g. "\\SYNOLOGY\web\wwwroot
 - > > .vscode
 - > > > launch.json

Your launch.json:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for Xdebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "log": true,
            "pathMappings": {
                "/": "${workspaceRoot}/"
            },
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000,
            "log": true,
            "pathMappings": {
                "/": "${workspaceRoot}/"
            },
        }
    ]
}
```

If I try to add a breakpoint into e.g. "index.php" I get an error eg:
Unable to open 'index.php': Unable to read file '\web\wwwroot\index.php' (Error: Unable to resolve non-existing file '\web\wwwroot\index.php').

I get a button option to "Create file" which windows explorer reveals that it has created this path under "C:"

I can hit the site (wordpress) on e.g. "dev.wordpress.com" but if i try adding "hostname" to the configuration this does not appear to make any difference.

For pathMappings I am unsure as to which side is client and which is remote - trying both ways around really hasn;t made a great deal of difference

I can follow instructions pretty well, but now constrained by ignorance... just need a couple of pointers to get past this hump.

Help appreciated.

**Comment by zobo** [comment]
Hi. I'll try to help as much as I can, but since I don't have all info about your setup I'll make some guesses.

1. dev.wordpress.com actually exists on the internet, but I'm guessing this is something on your local network - so perhaps a `dev.wordpress.local` example would make more sense - just a suggestion to keep things more understandable.
2. Since you did not add a Xdebug.log I'm gonna go ahead and guess the real location of the PHP files on your Synology. According to [docs](https://www.synology.com/en-global/knowledgebase/DSM/help/WebStation/application_webserv_general) it could be `/volume1/web/wwwroot`. 
3. You can access the files, as you stated, via UNC `\\SYNOLOGY\web\wwwroot`.

As the readme already states the path mappings are server->local. Meaning, the key on the left side is how PHP/Xdebug see files and the value on the right side is how VSCode sees the files. Path mappings are used to "replace" the prefix of the path. So in your case it should be:
```
            "pathMappings": {
                "/volume1/web/wwwroot": "\\\\SYNOLOGY\\web\\wwwroot"
            },
```

Note, on the left side the path is in POSIX format (forward slashed) where on the right side it is Win32 format (backslashes) - since server is Linux and client is Win10. And since this is JSON backslashes need to be doubled due to escaping.

Or if you want to use the VSCode provided variable:
```
            "pathMappings": {
                "/volume1/web/wwwroot": "${workspaceFolder}"
            },
```
`${workspaceRoot}` would also work.

You can find out what the exact server path of the files is by opening a file with `phpinfo();` or a similar method in a browser.

I understand this is a complex issue and it would deserve better explanation in the docs...

I hope this helps!

**Comment by Wishville** [comment]
Hi,

that's brilliant. I was one backslash off on one of my previous attempts having got as far as "\\\SYNOLOGY\\web\\wwwroot"

This now all works fine on "Listen for Xdebug" but "Launch currently open script" still throws an error:

Unable to open 'index.php': Unable to read file '\WEB\wwwroot\index.php' (Error: Unable to resolve non-existing file '\WEB\wwwroot\indext.php').

Looking in debug console I can see e.g.

```
-> stackTraceRequest
{
  command: 'stackTrace',
  arguments: { threadId: 1, startFrame: 0, levels: 20 },
  type: 'request',
  seq: 25
}
<- stackTraceResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 25,
  command: 'stackTrace',
  success: true,
  body: {
    stackFrames: [
      {
        id: 2,
        name: '{main}',
        source: {
          name: 'index.php',
          path: '/WEB/wwwroot/index.php'
        },
        line: 55,
        column: 1
      }
    ]
  }

}```

I have literally no idea where this "**\WEB\**" is coming from  - could I put a second pathmapping in to 'trap' for this?

**Comment by zobo** [comment]
Hi!

In the context you are describing (synology) "Launch script" doesn't really make sense. You are looking at remote files, but launch happens on your PC.

If this is what you want (run php-cli in your PC from remote path) I think there's a problem how UNC paths are presented by Xdebug. I'll look into it, but it would help if you could give me also your xdebug.log and confirm you are running the script on windows.

**Comment by Wishville** [comment]
Hi.

Can confirm I am running VS Code on Windows 10 Pro (version 20H2 / OS Build 19042.867)

I can't get xdebug to log anything :(

as per phpinfo I have configured to a location that should be writable

`xdebug.remote_log | /volume1/web/logs/xdebug.log -- | --`

But nothing gets added....

**Comment by Wishville** [comment]
Just an update:

I added a second pathMappings value to the "Launch currently open script" configuration which stops the error from appearing.

```
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000,
            "log": true,
            "pathMappings": {
                "/WEB/wwwroot": "\\\\wishville\\web\\wwwroot",
                "/volume1/web/wwwroot": "\\\\SYNOLOGY\\web\\wwwroot"                
            },
        }
```

It is definitely a better experience to be using the "Listen for Xdebug" and initiate from browser though.

**Comment by zobo** [comment]
The second line seems alright. But I have recently seen some mapping issues Xdebug has with UNC paths. I strongly suggest you do a drive map on windows and use that. For example:   S: -> \\SYNOLOGY\web and then  `"/volume1/web/wwwroot": "S:\\wwwroot"`.

Launch script would run the code on your PC, not on Synology, where as Listen just waits for a connection. This is, at least in this case, the correct approach.

Best!

**Comment by 2dareis2do** [comment]
I had similar issue and was able  to fix by switching out version of php and xdebug.

**Comment by zobo** [comment]
Can you share what versions were that (those that worked and those that did not)?
