### ISSUE TITLE
reverse server/local in pathMappings

### ISSUE THREAD

**Issue by jianzhong** [xdebug/vscode-php-debug#554]
Hi,

I wonder if we can reverse the key/value in pathMappings in launch.json? I mean instead of:
```
    "pathMappings": {
        "/var/www/vhost/frontend/app": "${workspaceRoot}/frontend",
        "/var/www/vhost/backend1/app": "${workspaceRoot}/backend1",
        "/var/www/vhost/backend2/app": "${workspaceRoot}/backend2"
    },
```
it would be good to be like this:
```
    "pathMappings": {
        "${workspaceRoot}/frontend": "/var/www/vhost/app",
        "${workspaceRoot}/backend1": "/var/www/vhost/app": ,
        "${workspaceRoot}/backend2": "/var/www/vhost/app": 
    },
```

This would be useful for debugging multi-containers application. In the above example, the project root on my local has 3 subfolders: frontend, backend1, backend2. Each subfolder is an app which can be running in a docker container, and all containers may have the same web root, such as /var/www/vhost/app. If we use the remote path as the key in the pathMappings, in my case all 3 containers have the same web root, the mapping would be invalid in json as the keys are duplicate. I could work this around by using different web root for each container, but it would be nicer to be able to reserse the mapping which would be really helpful for my real project which has nearly 100 containers.

**Comment by zobo** [comment]
Hi.
Reversing the current syntax would wreck havoc for millions of existing users projects. And it would actually not solve the issue you are having, at least not fully.
The mapping is used both ways. When the IDE needs to open a file (remote->local) and when setting a breakpoint (local->remote). So even if the duplicate key is solved, how would the IDE know what file to show you if Xdebug tells it to open `/var/www/vhost/app/file1.php` ?

This is a very similar issue to #522 .

In case you had only a few containers, I'd suggest using different ports to separate instances. But since you are saying its 100s containers...

What's your workflow? Debug just one container? Debug all of them at once?

I did manager to setup a complex example where I created a workspace with two folders, each containing each own `launch.json` and running on different ports. This way each could have their own path mappings.

![image](https://user-images.githubusercontent.com/2456026/116449212-397dc980-a85a-11eb-8dd8-08c9742b8d75.png)

![image](https://user-images.githubusercontent.com/2456026/116449329-5a461f00-a85a-11eb-8ae6-8cab34bca162.png)

This is probably not what you are looking for as for 100 sub projects this would be very difficult to maintain...

Let me know some specifics and perhaps I can figure out a direction for a solution to this kinds of multi project problems...

**Comment by jianzhong** [comment]
Hi,

Thanks for your reply. This is what the app looks like:

<img width="244" alt="Screenshot 2021-04-29 at 13 04 30" src="https://user-images.githubusercontent.com/1597492/116549949-08e76f80-a8ee-11eb-8be6-7c918da4adec.png">

The picture shows a similar but much smaller project structure. Docker-compose spins up 3 containers: frontend, backend1 and backend2. The _frontend_ receives user requests. The _backend1_ and _backend2_ are api services. The _backend1_ handles requests coming from the _frontend_. It would also send requests to _backend2_. Let's say this is a 3 layers application. But real project is much complex than this one and has a lot more layers and also at much large scale. All app containers are running together via docker-compose in dev environment. Each container has a xdebug.ini with `xdebug.client_host=host.docker.internal` and `xdebug.client_port=10000`, so I can open a single vscode window to step debug them all together on port 10000.

I did tried using different port for each app container, and it worked well for smaller project like the example I used here. For the real project, I realised I'd have to create 100s of xdebug.ini and launch.json files, and also have to open many vscode windows too when debuging them. Then I realised the value of using the pathMappings configuration. The only issue I have is to change web roots for some of sub-applications in my project, so I just want to see if it is possible to reverse the key/value in the pathMappings. Now I understand xdebug is sending a file's remote path to IDE and it has to be unique for IDE to identify the correct file locally. So, let it be, not a big deal. Thank you for the explaination.

**Comment by zobo** [comment]
I understand the problem. The suggestion I provided above lets you run multiple debuggers inside one window, but a workspace, joining together different sub-folders (with their own launch.json) would need to be created. But as you said, that doesn't solve cases with a very large number of projects.

If you'd like, you can _watch_ the other issue and see if I make any progress there - I'm not yet sure I want to implement it like that but it would solve your specific problem. However I'd much rather have a more generic approach in line with VS Code concepts.

Since reversing pathMappings wouldn't make sense, I'm closing this issue.
