### ISSUE TITLE
Documentation error ++ Portnumber for xdebug v2.x

### ISSUE THREAD

**Issue by gordiang** [xdebug/vscode-php-debug#635]
Hello,
the online documentation says:

---------------------------------
For Xdebug v2.x.x:
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
xdebug.remote_port = 9003
---------------------------------

BUT
**it must be port 9000 !!**

In the documentation a few lines below it is explained correctly:

---------------------------------
 Please note that the default Xdebug port changed between Xdebug v2 to v3 from 9000 to 9003.
---------------------------------

**Comment by zobo** [comment]
Hi. Since I introduced separate configuration templates for legacy Xdebug it would perhaps not make sense to instruct users to change the default Xdebug2 port to 9003.
The README is still from before that time, where the plugin port would always be 9003 (by default).

Maybe I should change the readme to say `xdebug.remote_port=9000` even though this is the Xdebug2 default, just to hint the user they can change it...

**Comment by zobo** [comment]
I've made a change in the docs leaving the default Xdebug v2 port and noting that there are special configurations for legacy installs.

In the end it's up to the user to choose how they want their setup...
