### ISSUE TITLE
debugger is not stopping on breakpoints

### ISSUE THREAD

**Issue by gentig** [xdebug/vscode-php-debug#653]
PHP version: 7.4
Xdebug version: 3.0.4
VS Code extension version: 1.60.0

Your launch.json: {
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for Xdebug",
            "type": "php",
            "request": "launch",
            "port": 9000
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 0,
            "runtimeArgs": [
                "-dxdebug.start_with_request=yes"
            ],
            "env": {
                "XDEBUG_MODE": "debug,develop",
                "XDEBUG_CONFIG": "client_port=${port}"
            }
        },
        {
            "name": "Launch Built-in web server",
            "type": "php",
            "request": "launch",
            "runtimeArgs": [
                "-dxdebug.mode=debug",
                "-dxdebug.start_with_request=yes",
                "-S",
                "localhost:0"
            ],
            "program": "",
            "cwd": "${workspaceRoot}",
            "port": 9003,
            "serverReadyAction": {
                "pattern": "Development Server \\(http://localhost:([0-9]+)\\) started",
                "uriFormat": "http://localhost:%s",
                "action": "openExternally"
            }
        }
    ]
}

**Comment by zobo** [comment]
Hi. If it doesn't stopOnEntey it probably means that Xdebug doesn't start or it looks for the IDE on a wrong port. I see you define listen port 9000 but Xdebug 3 default port is 9003. Can you check xdebug is running by inserting xdebug_info() on the top of your script you are trying to debug?

**Comment by gentig** [comment]
You are right I believe it is timing out. Here is what the message says. 
![image](https://user-images.githubusercontent.com/11341922/133260750-e20b9eaa-19ae-4fa9-954c-0ff70c470013.png)
xdebug connects fine from another IDE using session, I don't know why is timing out for vscode. vscode is listening to port 9003 now. Any ideas what is going on. Thank you

**Comment by zobo** [comment]
I see host.docker.internal. There was an issue here where vs code caused the extension to not listen on all interfaces. 
Try to check first if host.docker.internal correctly resolves. I'll try to find the other issue.

**Comment by zobo** [comment]
Here. Altho this is specific to vscode remote ssh and forwarded ports. https://github.com/xdebug/vscode-php-debug/issues/601#issuecomment-866467459
Check that after starting listen port your system actually lists that in netstat. Check that the xdebug.client_host actually resolves and try a fixed IP.

**Comment by gentig** [comment]
Adding "hostname": "localhost" and 
 "pathMappings": {
"/container/files/path": "${workspaceRoot}"
 }
fixed the problem.

**Comment by zobo** [comment]
Hi @gentig !
Great that you got it working. Would you be willing to share with me a bit more about your setup, so I can understand what is happening, and provide better documentation.

First, you said `VS Code extension version: 1.60.0`, but the current version is 1.17.0. Can you check that?
Second, I can't make out what OS you are on. Are you on windows with docker desktop, are you on a linux or mac with docker engine? Are you perhaps using vscode remote?
Third, can you share parts of you docker container configuration? If you use docker-compose, the parts about volume mounting, and if there are any specific network configuration (explicit host.docker.internal) ?
If you take a script in you project, and do a `var_dump(__FILE__);` how is it compared to the path you see the file in vscode?

I'm asking all of this, because `"hostname": "localhost"` doesn't make much sense, as it would bind the listen socket to localhost and that should prevent Xdebug from connecting to it, not allow it - if the idea of your setup I am having is correct.

Thanks a lot and happy debugging.

**Comment by gentig** [comment]
Hi @zobo,

So let me give you some info about the environment. I am on windows 10, and I have docker for win installed and configured with WSL2. xdebug is running inside the image container and docker recommends connecting to the host using host.docker.internal (https://docs.docker.com/desktop/mac/networking/). For some reason my launch.json was deleted out of no where and when I created the new config I forgot to add host and pathMappings. I saw that I had to add the host somewhere (Don't remember exactly ). I hope this helps.

**Comment by wwhurley** [comment]
I'm having an issue that might be similar. When using Docker Desktop installed on Windows with WSL2 the `host.docker.internal` address points to the Windows host. Previously using that would end up triggering XDebug in VSCode, but recently that is not the case. I've needed to grab the IP address from the WSL2 session and inject that into the containers and use that for `xdebug.client_host` in order to get it to work.
