### ISSUE TITLE
Debugger does not run on Mac OS

### ISSUE THREAD

**Issue by seyedrezabazyar** [xdebug/vscode-php-debug#697]
PHP version: 8.1
Xdebug version: 3.1
VS Code extension version: last version

Hello

I'm installed VSCode

When I run the following command in the VScode terminal:
```
 php -v                                                  
PHP 8.1.0 (cli) (built: Nov 28 2021 02:36:02) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.0, Copyright (c) Zend Technologies
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans
    with Zend OPcache v8.1.0, Copyright (c), by Zend Technologies
```

When I run a page containing the following code in the browser: 
‍‍`phpinfo();` >>> `https://i.stack.imgur.com/hRkOZ.png`

Now when I debug the code, I encounter this error in VSCODE environment

```
[Tue Dec  7 10:13:14 2021] PHP 8.1.0 Development Server (http://localhost:50274) started
[Tue Dec  7 10:13:15 2021] [::1]:50276 Accepted
[Tue Dec  7 10:13:15 2021] [::1]:50276 [404]: GET / - No such file or directory
[Tue Dec  7 10:13:15 2021] [::1]:50276 Closing
[Tue Dec  7 10:13:15 2021] [::1]:50277 Accepted
[Tue Dec  7 10:13:15 2021] [::1]:50277 [404]: GET /favicon.ico - No such file or directory
[Tue Dec  7 10:13:15 2021] [::1]:50277 Closing
```

When I run the debugger in the browser:

Link: http://localhost:50274
‍‍`
Not Found
The requested resource / was not found on this server.
`

What is the solution to these problems? How do I enable debugger?

**Comment by zobo** [comment]
Hi!
The screenshot of phpinfo doesn't help much, since it doesn't show if Xdebug is loaded and what its settings are.

1. your command line php seems ok - the first snippet.
2. your image of phpinfo() seems to come from an Apache. Is Xdebug loaded there? Either in /Applications/XAMPP/xamppfiles/etc/php.ini or any other included ini files?
3. the last snippet seems to be the built in web server.

I also see that your first and last snippets show the same PHP installation (8.1.0) where as apache uses 8.0.6.

Now, I am guessing you are trying to debug a web application. There are two options:
Configure Apache+PHP+Xdebug or user built in PHP web server.

The build in PHP web server is easier, but might not support everything you need (apache url rewrites...).
If your launch.json file, you can add the configuration snippet `PHP: Launch Built-in web server`.

It looks like this:
```
        {
            "name": "Launch Built-in web server",
            "type": "php",
            "request": "launch",
            "runtimeArgs": [
                "-dxdebug.mode=debug",
                "-dxdebug.start_with_request=yes",
                "-S",
                "localhost:0"
            ],
            "program": "",
            "cwd": "${workspaceRoot}",
            "port": 9003,
            "serverReadyAction": {
                "pattern": "Development Server \\(http://localhost:([0-9]+)\\) started",
                "uriFormat": "http://localhost:%s",
                "action": "openExternally"
            }
        }
```

What you need to be careful about is the `cwd`. By default it sets your document root to your workspace root. But if you keep your (for example) `index.php` in a subfolder like `public_html` you will need to change it to `"cwd": "${workspaceRoot}/public_html",`

Then select this configuration and click the green arrow.

![image](https://user-images.githubusercontent.com/2456026/145008122-33766c98-a9bd-436f-b9a3-45bf8fe04791.png)

Your web browser should also open, but it could be - depending on your project - that you will need to change the url by adding /index.php or whatever file you are opening.


Alternatively for Apache, you will need to get a different version of Xdebug (if it is not already included with that install), load it and configure it with `xdebug.mode=debug` and `xdebug.start_with_request=yes`. VS Code will need to run the `Listen for Xdebug` debug configuration.

Let me know how far you get and I can probably dig out some other material to help you.

**Comment by zobo** [comment]
No feedback, closing. Please reopen if this is still an issue for you. Provide Debug Console logs and xdebug_info() output.
