### ISSUE TITLE
Pass file content as stdin input

### ISSUE THREAD

**Issue by gmarsano** [xdebug/vscode-php-debug#814]
I believe that it is currently not possible to pass the contents of a file as stdin input for CLI executions.

I tried...
```
"externalConsole": true,
"args": ["<", "input.txt"]

# and with:

"args": ["<", "${fileDirname}/input.txt"]
```
... but the debug hangs waiting for an input.

**Comment by zobo** [comment]
Hi!

This will not work like that, because the debug adapter (this extension) spawns a php process and gives it the parameters.

If you look at the last section of https://github.com/xdebug/vscode-php-debug#supported-launchjson-settings there is a section "Options specific to CLI debugging". When starting a debug process, the following happens:

Working directory: $cwd
Process spawned: $runtimeExecutable
Arguments: $runtimeArgs $program $args
Environment variables: $env

So you could get the debug adapter to spawn shell and get it to use a file as stdin.

I can make a working example at a later date as I am currently traveling.

Alternatively I would suggest to use "Listen for Xdebug" and run your program in a separate shell. Set the `XDEBUG_MODE` env to debug.

`XDEBUG_MODE=debug php script.php < input.txt`

Let me know if you are able to solve the problem like this.

**Comment by gmarsano** [comment]
> Alternatively I would suggest to use "Listen for Xdebug" and run your program in a separate shell. Set the `XDEBUG_MODE` env to debug.
> 
> `XDEBUG_MODE=debug php script.php < input.txt`
> 
> Let me know if you are able to solve the problem like this.

Yes, that way worked.
I used the "Listen for Xdebug" setting in vscode.
```bash
export XDEBUG_MODE=debug
php script.php < input.txt
```

**Comment by zobo** [comment]
Great! I'll try to write a configuration with shell when I come back from my travels.

**Comment by zobo** [comment]
Here is an option:

```
		{
			"name": "TEST",
			"type": "php",
			"request": "launch",
			"cwd": "${workspaceFolder}",
			"port": 0,
			"env": {
				"XDEBUG_MODE": "debug,develop",
				"XDEBUG_CONFIG": "client_port=${port}"
			}
			"runtimeExecutable": "bash",
			"runtimeArgs": [
				"-c",
				"php -dxdebug.start_with_request=yes script.php < input.txt"
			]
		}
```

**Comment by gmarsano** [comment]
Thanks, It works! I made some changes for flexibility with script name or input location in case of using an external terminal.

```json
{
    "name": "Launch currently open script with input",
    "type": "php",
    "request": "launch",
    "cwd": "${fileDirname}",
    "port": 0,
    "runtimeExecutable": "bash",
    "runtimeArgs": [
        "-c",
        "php -dxdebug.start_with_request=yes ${file} < ${cwd}/input.txt"
    ],
    "env": {
        "XDEBUG_MODE": "debug,develop",
        "XDEBUG_CONFIG": "client_port=${port}"
    }
}
```
